Client.Persistence.WebApp/Controllers/ClientController.cs
using Client.Persistence.Core.Client.Service.Interface;
using Client.Persistence.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Client.Persistence.WebApp.Controllers
{
    public class ClientController : Controller
    {
        private string _filePath;
        private readonly IClientService? _clientservice;

        public ClientController(IWebHostEnvironment filePath, IClientService? clientservice)
        {
            _filePath = filePath.WebRootPath;
            _clientservice = clientservice;
        }

        // GET: ClientController
        [HttpGet("clientes")]
        public async Task<IActionResult> Index()
        {
            return View(await _clientservice.GetAllAsync());
        }

        // GET: ClientController/Details/5
        [HttpGet("cliente/detalhe")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _clientservice.GetWithPublicAreaAsync(id));
        }

        // GET: ClientController/Create
        [HttpGet("cliente/adicionar")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: ClientController/Create
        [HttpPost("cliente/adicionar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersistenceViewModel entity, IFormFile file)
        {
            if(!isValidImage(file))
                return View(entity);

            var name = await SaveFile(file);
            entity.Client.Logo = name;

            if(ModelState.IsValid){
                entity.Client.PublicAreas.Add(entity.PublicArea);
                await _clientservice.CreateAsync(entity?.Client);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");
        }

        // GET: ClientController/Edit/5
        [HttpGet("cliente/editar")]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _clientservice.GetAsync(id));
        }

        // POST: ClientController/Edit/5
        [HttpPost("cliente/editar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Core.Client.Model.Client entity, IFormFile file)
        {
            string filePathName = $"{_filePath}\\images\\{entity.Logo}";

            if (!System.IO.File.Exists(filePathName)){

                if (!isValidImage(file))
                    return View(entity);

                var name = await SaveFile(file);
                entity.Logo = name;
            }            

            if (ModelState.IsValid){
                await _clientservice.UpdateAsync(entity);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");

        }

        // GET: ClientController/Delete/5
        [HttpGet("cliente/deletar"), ActionName("Delete")]
        public async Task<IActionResult> DeleteView(int id)
        {
            return View(await _clientservice.GetAsync(id));
        }

        // POST: ClientController/Delete/5
        [HttpPost("cliente/deletar"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var client = await _clientservice.GetAsync(id);
            string filePathName = $"{_filePath}\\images\\{client.Logo}";

            if(System.IO.File.Exists(filePathName))
                System.IO.File.Delete(filePathName);

            if(ModelState.IsValid){
                await _clientservice.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");
        }

        private bool isValidImage(IFormFile file)
        {
            return file.ContentType switch
            {
                "image/jpeg" => true,
                "image/bmp" => true,
                "image/gif" => true,
                "image/png" => true,
                _ => false
            };
        }

        private async Task<string> SaveFile(IFormFile file)
        {
            var name = file.FileName;

            var filePath = $"{_filePath}\\images";

            if (!Directory.Exists(filePath))
            {
                Directory.CreateDirectory(filePath);
            }

            using (var stream = System.IO.File.Create($"{filePath}\\{name}"))
            {
                await file.CopyToAsync(stream);
            };

            return name;
        }
    }
}

Client.Persistence.WebApp/Controllers/PublicAreaController.cs
using Client.Persistence.Core.PublicArea.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace Client.Persistence.WebApp.Controllers
{
    public class PublicAreaController : Controller
    {
        private readonly IPublicAreaService? _publicAreaService;

        public PublicAreaController(IPublicAreaService? publicAreaService)
        {
            _publicAreaService = publicAreaService;
        }

        // GET: PublicAreaController
        [HttpGet("logradouro")]
        public async Task<IActionResult> Index()
        {
            return View(await _publicAreaService.GetAllAsync());
        }

        // GET: PublicAreaController/Details/5
        [HttpGet("logradouro/detalhe")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await _publicAreaService.GetAsync(id));
        }

        // GET: PublicAreaController/Create
        [HttpGet("logradoura/adicionar")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: PublicAreaController/Create
        [HttpPost("logradoura/adicionar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Core.PublicArea.Model.PublicArea entity)
        {
            if (ModelState.IsValid){
                await _publicAreaService.CreateAsync(entity);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");
        }

        // GET: PublicAreaController/Edit/5
        [HttpGet("logradouro/editar")]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _publicAreaService.GetAsync(id));
        }

        // POST: PublicAreaController/Edit/5
        [HttpPost("logradouro/editar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Core.PublicArea.Model.PublicArea entity)
        {
            if (ModelState.IsValid){
                await _publicAreaService.UpdateAsync(entity);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");
        }

        // GET: PublicAreaController/Delete/5
        [HttpGet("logradouro/deletar"), ActionName("Delete")]
        public async Task<IActionResult> DeleteView(int id)
        {
            return View(await _publicAreaService.GetAsync(id));
        }

        // POST: PublicAreaController/Delete/5
        [HttpPost("logradouro/deletar"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if(ModelState.IsValid){
                await _publicAreaService.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            else
                return View("Error");
        }
    }
}

Client.Persistence.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consulta de Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.Persistence.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consulta de Clientes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PublicArea" asp-action="Index">Logradouros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Consulta de Clientes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>